// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	repository2 "nexai-backend/internal/code/repository"
	cache2 "nexai-backend/internal/code/repository/cache"
	service2 "nexai-backend/internal/code/service"
	"nexai-backend/internal/common/jwt"
	"nexai-backend/internal/common/sms/memory"
	"nexai-backend/internal/user/handler"
	"nexai-backend/internal/user/repository"
	"nexai-backend/internal/user/repository/cache"
	"nexai-backend/internal/user/repository/dao"
	"nexai-backend/internal/user/service"
)

// Injectors from wire.go:

func InitUserHandler() *handler.UserHandler {
	logger := InitLogger()
	db := InitMySQL()
	userDAO := dao.NewGORMUserDAO(db)
	cmdable := InitRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(logger, userRepository)
	codeCache := cache2.NewRedisCodeCache(cmdable)
	codeRepository := repository2.NewCachedCodeRepository(codeCache)
	smsService := memory.NewService()
	codeService := service2.NewCodeService(codeRepository, smsService)
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := handler.NewUserHandler(logger, userService, codeService, jwtHandler)
	return userHandler
}

func InitWebServer() *gin.Engine {
	logger := InitLogger()
	db := InitMySQL()
	userDAO := dao.NewGORMUserDAO(db)
	cmdable := InitRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(logger, userRepository)
	codeCache := cache2.NewRedisCodeCache(cmdable)
	codeRepository := repository2.NewCachedCodeRepository(codeCache)
	smsService := memory.NewService()
	codeService := service2.NewCodeService(codeRepository, smsService)
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := handler.NewUserHandler(logger, userService, codeService, jwtHandler)
	engine := InitGinServer(userHandler, jwtHandler)
	return engine
}

// wire.go:

var thirdParty = wire.NewSet(
	InitLogger,
	InitMySQL,
	InitRedis,
)

var userSvc = wire.NewSet(cache.NewRedisUserCache, dao.NewGORMUserDAO, repository.NewCachedUserRepository, service.NewUserService)

var codeSvc = wire.NewSet(cache2.NewRedisCodeCache, repository2.NewCachedCodeRepository, service2.NewCodeService, memory.NewService)
