server:
  mode: "debug"

log:
  level: "debug"
  path: "./storage/logs/app.log"
  max_size: 1  # 日志最大 1000 M
  max_age: 3600   # 日志保留天数
  max_backups: 5  # 最多保留 5 个备份文件

mysql:
  dsn: "root:root@tcp(127.0.0.1:13306)/nexai?charset=utf8mb4&parseTime=True&loc=Local"

postgres:
  dsn: "host=localhost user=postgres password=root dbname=nexai port=15432 sslmode=disable TimeZone=Asia/Shanghai"

redis:
  address: "127.0.0.1:16379"

kafka:
  addr:
    - "localhost:9094"

llm:
  provider: "ark"
  region: "cn-beijing"
