// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"nexai-backend/cmd/server/ioc"
	repository2 "nexai-backend/internal/code/repository"
	cache2 "nexai-backend/internal/code/repository/cache"
	service2 "nexai-backend/internal/code/service"
	"nexai-backend/internal/common/jwt"
	"nexai-backend/internal/user/handler"
	"nexai-backend/internal/user/repository"
	"nexai-backend/internal/user/repository/cache"
	"nexai-backend/internal/user/repository/dao"
	"nexai-backend/internal/user/service"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	logger := ioc.InitLogger()
	v := ioc.InitGinMiddlewares(jwtHandler, logger)
	db := ioc.InitPostgreSQL(logger)
	userDAO := dao.NewGORMUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(logger, userRepository)
	codeCache := cache2.NewRedisCodeCache(cmdable)
	codeRepository := repository2.NewCachedCodeRepository(codeCache)
	smsService := ioc.InitSMSService()
	codeService := service2.NewCodeService(codeRepository, smsService)
	userHandler := handler.NewUserHandler(logger, userService, codeService, jwtHandler)
	engine := ioc.InitWebEngine(v, logger, userHandler)
	app := &App{
		engine: engine,
	}
	return app
}

// wire.go:

var thirdParty = wire.NewSet(ioc.InitLogger, ioc.InitPostgreSQL, ioc.InitRedis)

var userSvc = wire.NewSet(cache.NewRedisUserCache, dao.NewGORMUserDAO, repository.NewCachedUserRepository, service.NewUserService)

var codeSvc = wire.NewSet(cache2.NewRedisCodeCache, repository2.NewCachedCodeRepository, ioc.InitSMSService, service2.NewCodeService)
