// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package main

import (
	ioc2 "nexai-backend/cmd/server/ioc"
	coderepo "nexai-backend/internal/code/repository"
	codecache "nexai-backend/internal/code/repository/cache"
	codeservice "nexai-backend/internal/code/service"
	"nexai-backend/internal/common/jwt"
	"nexai-backend/internal/user/handler"
	userrepo "nexai-backend/internal/user/repository"
	usercache "nexai-backend/internal/user/repository/cache"
	"nexai-backend/internal/user/repository/dao"
	userservice "nexai-backend/internal/user/service"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc2.InitLogger()
	db := ioc2.InitMySQL(logger)
	redisClient := ioc2.InitRedis()
	userCache := usercache.NewRedisUserCache(redisClient)
	userDAO := dao.NewGORMUserDAO(db)
	userRepo := userrepo.NewCachedUserRepository(userDAO, userCache, logger)
	userService := userservice.NewUserService(logger, userRepo)
	codeCache := codecache.NewRedisCodeCache(redisClient)
	codeRepo := coderepo.NewCachedCodeRepository(codeCache)
	smsService := ioc2.InitSMSService()
	codeService := codeservice.NewCodeService(codeRepo, smsService)
	jwtHandler := jwt.NewRedisJWTHandler(redisClient)
	userHandler := handler.NewUserHandler(logger, userService, codeService, jwtHandler)
	middlewares := ioc2.InitGinMiddlewares(jwtHandler, logger)
	engine := ioc2.InitWebEngine(middlewares, logger, userHandler)
	app := &App{
		engine: engine,
	}
	return app
}
